# Generated by Django 5.2.6 on 2025-09-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sale_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
